---
date: "2021-12-01T00:00:00Z"
#external_link: ""
image:
  caption: 
  focal_point: Smart
# links:
# - icon: github
#   icon_pack: fab
#   name: Github materials
#   url: https://github.com/dong316/meta
# slides: example
summary: 'Research proposal in AGRY649 (Molecular Microbial Ecology)' 
tags:
- microbiome
title: Understanding the effects of microbial maturation on pig growth using multi-omics analysis and gnotobiotic mice model
url_code: ""
url_pdf: ""
url_slides: ""
url_video: ""
---

__Overview__

Our preliminary study indicated both birth weight and antibiotic growth promoters (AGP) have a significant impact on pig growth performance. Recently, the role of the gut microbiome on animal growth performance has been widely acknowledged. However, the mechanisms  remain unclear of how much proportion of growth variation can be explained by the microbial community, how the gut symbiont regulates the nutrient absorption and utilization, and the host response to the fluctuation of the gut microbiome. 
To understand the effects of the gut microbiome on growth performance, our proposal have the following 2 parts: 1) characterize clear gut microbial maturation patterns (colonization & succession) in pigs with different birth weights and treated with AGP or not; 2) use gnotobiotic mice model to determine the “true” effect size of the gut microbiome on pig growth. 

The dynamics of swine gut microbial development from nursery and weaning toward an adult pattern is poorly characterized. The previous “snapshot” comparison is incomplete with the influence of natural variations and transient dynamics. To fill the knowledge gap, the objective of the first study is to determine a clear pattern of microbial development in pigs with different growth and body conditions. A longitudinal microbial community analysis with high-frequency sampling (2 days interval) will be conducted during the entire nursery and weaning periods. High-throughput 16S rRNA gene and shotgun meta-genomics sequencing will be used to profile the compositional and functional development of the gut microbial community. 

Gnotobiotic mice models have made enormous contributions to human disease and nutritional research and showed a promising future in microbiome study. The second study will use gnotobiotic mice models to determine whether the growth retardation caused by low birth weight or growth promotion caused by AGP are causally related with gut microbiota in pigs. Gnotobiotic mice models colonized with microbiome from pigs will be established with the fecal samples from study 1. Body weight and composition, immune response, and multi-omics analysis to the gut microbial profile (16S rRNA, shotgun metagenomics, and microbial RNA seq following the central dogma) of mice models will be used to future extract the “true” contribution from the gut microbiome to the growth in pigs.

__Intellectual Merits__

This proposal will generate a high-resolution “image” of the swine gut microbiome development. By determining the detailed succession of the intestinal microbiome, this study will serve as a benchmark comparison for all microbiome studies and will accelerate the discovery of probiotic strains. The gnotobiotic mice model will elucidate the causal relationship between gut microbiota and growth retardation.

__Broader Impacts__

This proposal will have the following broader impacts: 1) The proposed work will increase the relationship between academia and the swine industry because the academia will provide detailed microbial inference toward growth retardation. 2) This proposal will facilitate the development of microbial stewardship in pigs and reduce the use of antibiotics as growth promoters. 3) The current study will provide potential microbial approaches to deal with the health problems in pigs and reduce the economic losses caused by growth retardation.