---
date: "2022-07-01T00:00:00Z"
# external_link: ""
image:
  caption: 
  focal_point: Smart
# links:
- icon: github
  icon_pack: fab
  name: Github materials
  url: https://github.com/dong316/meta
# slides: example
summary: 'Keywords: meta analysis, swine gut microbiome, closed-reference OTU picking, individual participant data' 
tags:
- microbiome
title: IPD meta-analysis on the dynamical development of the swine gut microbiome
url_code: ""
url_pdf: ""
url_slides: ""
url_video: ""
---

__Background__: Understanding the mechanisms of microbiome assembly during host development is critical to the regulation of host health and growth through modulating the gut microbiome. Despite a large number of research in the microbiome modulation, limitations still exist in the pig microbiome management. Previous cross-sectional comparisons or longitudinal investigations with large time intervals did not attempt to elucidate the dynamics of the swine gut microbiome on a daily timescale. The incomplete characterization of the swine gut microbiome limits our ability to understand the impacts of various animal treatments on microbial community development due to the transient dynamics and natural variations.

__Results__: A total of 3,313 fecal samples covering 60 time points (from birth to marketing) of 349 pigs from 14 studies published from 2019 to 2021 were included in this meta-analysis. Raw sequences were analyzed in the QIIME2 program (2021.11) and a closed-reference OTU picking approach was used. Alpha diversity, measured by Faith PD, Pielou’s evenness, Shannon index, and the number of observed features, showed a continuous increase during the early stages (before 60 days of life) and a slow change in the following stages. The microbial community structure also changed significantly between days at early ages and became more similar as pigs grow older, as revealed by beta dissimilarity or distance matrixes. Dirichlet multinomial mixtures (DMM) analysis supported a gradient microbial cluster strategy in analyzing longitudinal pig fecal samples and we found the samples from growing and finishing period clustered into 4 main groups while early samples spread into all 10 clusters. Random forest regression identified 30 OTUs as potential biomarkers in modeling the swine gut microbiome development and the prediction models performed better in early stages with highly variable community configurations. External validation proved the generalization and benchmarking role of our models in application to future microbiome studies conducted in suckling and weaning pigs.

__Conclusions__: To sum up, our study described the swine gut microbiome development with a clear view and high resolution by combining multiple datasets. We observed an allometric assembly pattern of the swine gut microbiome with a developmental phase at early ages and a stabilization phase at late ages. Shortened time interval and comprehensive coverage of the data source provide us insight into the microbiome-derived swine healthy promotion strategies development. The rapid changing microbiome of suckling and weaning pigs implies potential time targets for growth and health regulation through gut microbiome. 